# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 

menu:
- {name: 'Perihal',   url: 'perihal.html'}
- {name: 'Arsip', url: 'arsip.html'}
- {name: 'Kontak', url: 'kontak.html'}
- {name: 'Sekarang', url: 'sekarang.html'}

  # Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope',   link: 'mailto:al1r4d@riseup.net'}
- {icon: 'rss-square', link: '/feed.xml'}
- {icon: 'telegram', link : 'https://t.me/al1r4d'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Terbaru'
  previous_page: 'Terlama'

sharing_button_prompt: 'Boleh dishare'

related_posts: 'Terkait'

post_date_prefix: 'Ditulis pada'
